# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbdc83733c8bef70036d503822de8dd041d98e70750ee003c6ecd496e83270bfe7584018ba1f2fc850594c885a606a1ab9d6331f0d93ddcb47073d3b10e7bfea

test:
  secret_key_base: 40c59b5585758ca648b78a9be542b28a9a1ac43c50fb1388c123e9fac242f7a4a59ee57325e26bdad44978510411d7d27cc56766591aa5931f7c863dba2206eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
